# Default values for micro-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ibmcase/bluecompute-auth
  tag: latest
  pullPolicy: Always

service:
  name: auth
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

ingress:
  enabled: true
  hostname: auth.bluecompute.com
  path: /oauth

tls:
  enabled: false
  secretName:
  crt: ENTER_BASE64_ENCODED_CERTIFICATE
  key: ENTER_BASE64_ENCODED_KEY

dataloader:
  image:
    repository: ibmcase/bluecompute-dataloader
    tag: latest

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi

customer:
  service:
    url:

hs256key:
  skipDelete: true
  secretName: hs256-key
  secret:

global:
  hs256key:
    secretName:
    secret:
