apiVersion: v1
entries:
  auth:
  - apiVersion: v1
    created: "2019-07-25T15:13:52.697593-05:00"
    description: A Helm chart for Kubernetes
    digest: 250e112cddaa38ba75279e44c712fd9099256c5ccdaa1504a65b6e796c9e2887
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: auth
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-auth/tree/microprofile
    urls:
    - auth-0.0.1.tgz
    version: 0.0.1
generated: "2019-07-25T15:13:52.696392-05:00"
